config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat = Flat.update(flat_params)
    @flat.save
    redirect_to edit_flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flat_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<br/>
<br/>
<h2>Edit a flat</h2>
<%= form_with model: @flat do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :price %>
  <%= f.text_field :price_per_night %>
  <%= f.label :guests %>
  <%= f.text_field :number_of_guests %>
  <%= f.submit %>
<% end %>
<br/>
<%= link_to "Back", flats_path %>

app/views/flats/index.html.erb
<div class="container">
<h2 class="text-center">All our Flats</h2>
<br/>
<div class="card-container row justify-content-center">
  <% @flats.each do |flat| %>
  <div class="col-md-3">
  <div class="card shadow mb-4" style="width: 20rem">
  <div class="card-body">
  <h3 class="card-title"><%= flat.name %></h3>
  <p class="card-subtitle"><%= flat.address %></p>
  <div class="d-flex flex-row">
  <div class="d-flex flex-row">
  <div class="p-2"><p class="card-text"><i class="fa-solid fa-bed"></i></div>
  <div class="p-2"><%= flat.number_of_guests %></p></div>
  </div>
  <div class="d-flex flex-row">
  <div class="p-2"><p class="card-text"><i class="fa-solid fa-euro-sign"></i></div>
  <div class="p-2"><%= flat.price_per_night %></p></div>
  </div>
  </div>
  <%= link_to "More info", flat_path(flat) %>
  <%= link_to "Edit", edit_flat_path(flat) %>
  <%= link_to "Remove", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </div>
  </div>
  </div>
  <% end %>
</div>
</div>

app/views/flats/new.html.erb
<br/>
<br/>
<h2>Add a flat</h2>
<%= form_with model: @flat do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :price %>
  <%= f.text_field :price_per_night %>
  <%= f.label :guests %>
  <%= f.text_field :number_of_guests %>
  <%= f.submit %>
<% end %>
<br/>
<%= link_to "Back", flats_path %>

app/views/flats/show.html.erb
<img id="map" style="width:30rem" src='https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/2.3381,48.8693,10.45,0,0/600x1000?access_token=pk.eyJ1IjoiaGFsaW1hLTY2IiwiYSI6ImNsc216cG5iazB0ZzkyanIxOHRqOGVjb3cifQ.ZaTOehpOvyLQIeWI0-TOZA'>
<h1><%= @flat.name %></h1>
<p><%= @flat.address %></p>
<p><%= @flat.description %></p>
<p>guests: <%= @flat.number_of_guests %></p>
<p>price: <%= @flat.price_per_night %></p>
 <br/>
 <%= link_to "Back", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand text-dark">Simple Airbnb</a>
   <div><button class='btn btn-outline-primary'><%= link_to "Add Flat", new_flat_path(@flat) %></button></div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>